### ISSUE TITLE
about the seed sequence

### ISSUE THREAD

**Issue by huangziyan11111** [BIONF/fDOG#19]
Hi, I want to make sure that the input single fasta file(seed sequence) means just one sequence in the file?

**Comment by trvinh** [comment]
Hi @huangziyan11111, 
yes, for `fdog.run` it must be a single fast file :) If you have several seed sequences, you can put them into one folder and use `fdogs.run`, see https://github.com/BIONF/fDOG/wiki/Use-standalone-version
Best,
Vinh

**Comment by trvinh** [comment]
btw, if you want to ask questions or discuss, please use this channel https://github.com/BIONF/fDOG/discussions ;) Many thanks!
