### ISSUE TITLE
Avoid editing `~/.bashrc` without user permission

### ISSUE THREAD

**Issue by paulmenzel** [BIONF/fDOG#25]
The setup script currently edits the user’s `~/.bashrc` in several places, for example:

https://github.com/BIONF/fDOG/blob/7a987e33f80e4761b0846f281ade59118978557b/fdog/setup/setup.sh#L138-L140

This should be avoided. It’d be nice if only instructions how to do it were printed by the script.

**Comment by trvinh** [comment]
Hi @paulmenzel, 
many thanks for the suggestion. Yes, it is not convenient in some instances. We are still looking for a better solution. May be just giving the instructions for the user to do that by themselves is a good option.

**Comment by paulmenzel** [comment]
In our environment, we have good experiences creating a profile script, like `fdog.profile`, which the users can manually use by sourcing it, and, if wanted, can be added to the individual per-interactive-shell startup file.

**Comment by trvinh** [comment]
It sounds great! I will check it and adapt this solution to the setup in the next version. Many thanks! :)

**Comment by trvinh** [comment]
solved with PR #26

**Comment by paulmenzel** [comment]
Thank you. Just a note, that you can add

> Resolves: https://github.com/BIONF/fDOG/issues/25

to a commit message, and GitHub is going to automatically close the issue, once the merge/pull request with that commit is submitted.

**Comment by trvinh** [comment]
Hi @paulmenzel, 
many thanks for the hint, I have learned something new from you, again! :) 
Btw, if you are using the latest version, there are some minor changes in the usage (for example `--seqNam` is changed to `--jobName`, and the data folders are also renamed). I am updating the [WIKI](https://github.com/BIONF/fDOG/wiki) to include those changes.
