### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '~/python3.7/lib/python3.7/site-packages/fdog/bin/pathconfig.txt'

### ISSUE THREAD

**Issue by erya-song** [BIONF/fDOG#28]
Hello,
I met this error when I setup fDOG:

Traceback (most recent call last):
  File "/public/home/HuCH/jxhuang/biosoft/python3.7/bin/fdog.setup", line 8, in <module>
    sys.exit(main())
  File "/public/home/HuCH/jxhuang/biosoft/python3.7/lib/python3.7/site-packages/fdog/setupfDog.py", line 256, in main
    with open(pathconfig_file, 'w') as cf:
**FileNotFoundError: [Errno 2] No such file or directory:** '/public/home/HuCH/jxhuang/biosoft/python3.7/lib/python3.7/site-packages/fdog/**bin/pathconfig.txt**

And I can not find the "bin" dictionary in the path "/public/home/HuCH/jxhuang/biosoft/python3.7/lib/python3.7/site-packages/fdog/", it presents as:
![image](https://user-images.githubusercontent.com/90766519/216875210-57d81eb0-4732-452c-80ac-1a4d3aa2300d.png)

How to solve this problem?
Thanks.

**Comment by trvinh** [comment]
Hi @erya-song
please try installing the v0.1.7 to see if the problem is solved.
Best,
Vinh

**Comment by erya-song** [comment]
Dear&nbsp;Vinh,


Thanks a lot.
The fdog has been installed successfully and worked. But I met a new issue when I add a new gene set (taxon) into fDOG. The command is:


fdog.addTaxon -f protome/AEV.fa -i 20340 -o lib91 -n AEV --replace -c


and met the erro:&nbsp;OSError: [Errno 39] Directory not empty: 'signalp_167839'


The details of the log was attached.


Hope your reply.


Best.
Yachao Wang
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Mon, Feb 6, 2023 09:28 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [BIONF/fDOG] FileNotFoundError: [Errno 2] No such file or directory: '~/python3.7/lib/python3.7/site-packages/fdog/bin/pathconfig.txt' (Issue #28)

&nbsp;



 
Hi @erya-song
 please try installing the v0.1.7 to see if the problem is solved.
 Best,
 Vinh

**Comment by trvinh** [comment]
Hi Yachao,
I have check your command with the first 50 sequences of the AEV.fa file and haven't had any issues with it. However, it seems that you have now problem with FAS. See:
```
Error running
/public/home/HuCH/jxhuang/wangyc/biosoft/FAStools/fLPS/fLPS -s -t 1e-07 "/public/home/HuCH/jxhuang/wangyc/wgd/hmstr/1taxa/lib91/annotation_dir/tmp/AEV@20340@230224_AEV_1000015.fa"
Error running
cat "/public/home/HuCH/jxhuang/wangyc/wgd/hmstr/1taxa/lib91/annotation_dir/tmp/AEV@20340@230224_AEV_1000001.fa" | /public/home/HuCH/jxhuang/wangyc/biosoft/FAStools/TMHMM/decodeanhmm -f /public/home/HuCH/jxhuang/wangyc/biosoft/FAStools/TMHMM//lib/TMHMM2.0.options -modelfile /public/home/HuCH/jxhuang/wangyc/biosoft/FAStools/TMHMM/lib/TMHMM2.0.model
...
```
Could you please try running this command only:
```
fas.doAnno -i test_annofas.fa -o test_output
```
Don't worry where the `test_annofas.fa` is, just run that command and check if there are any error messages. If not, please check for the output file in test_output folder (you can use any online JSON viewer to view the file), if all of the annotations are there (not all the proteins will have the complete annotation from all the tools PFAM, SMART, fLPS, SEG, COILS2, SignalP and TMHMM, but in the whole annotation file you will find at least one entry of each tool).
If you encounter any problems with that, please try to install FAS manually again (see https://github.com/BIONF/FAS and https://github.com/BIONF/FAS/wiki/setup). After the above command of `fas.doAnno` successfully run, you can check the demo command of fDOG
```
fdog.run --seqFile infile.fa --jobName test --refspec HUMAN@9606@3
```
If everything works fine without any error messages, you can use it with your own data.
You can directly write me via email (tran@bio.uni-frankfurt.de), if it is more convenient for you :)
Best,
Vinh
