### ISSUE TITLE
4180 low-copy lineologous candidate nuclear genes from 9 representative angiosperms

### ISSUE THREAD

**Issue by majssssa** [BIONF/fDOG#29]
Hello, I read an article about angiosperms phylogeny written by someone else and paid attention to your software. In the article, there appeared 4180 core low-copy nuclear gene data set composed of 9 angiosperms. May I ask whether these 4180 low-copy genes are in the pre-downloaded database? Or do I need to use software to extract from 9 angiosperms?

**Comment by trvinh** [comment]
Hello @majssssa, 
could you please give me the DOI number of the manuscript?
Regards,
Vinh

**Comment by majssssa** [comment]
Hello BIONF
The number of DOI is&nbsp;10.1038/ncomms5956.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BIONF/fDOG"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月27日(星期一) 凌晨3:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BIONF/fDOG] 4180 low-copy lineologous candidate nuclear genes from 9 representative angiosperms (Issue #29)





 
Hello @majssssa,
 could you please give me the DOI number of the manuscript?
 Regards,
 Vinh

**Comment by trvinh** [comment]
Hi @majssssa, 
Unfortunately, that the data in that paper is outdated and is not compatible with the current version of fDOG. However, if you want, we can provide you a new set of ortholog groups for the same taxa used in the paper (_A. thaliana, Glycine max, Medicago truncatula, Populus trichocarpa, Solanum lycopersicum, Vitis vinifera, Oryza sativa, Sorghum bicolor and Zea mays_), which can be used with fDOG.
Best,
Vinh

**Comment by majssssa** [comment]
Hi VinhThank you very much for your reply,May I know where I can download the new data?
Best,
Jun peng




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Vinh ***@***.***&gt;; 
发送时间: 2023年3月27日(星期一) 下午4:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [BIONF/fDOG] 4180 low-copy lineologous candidate nuclear genes from 9 representative angiosperms (Issue #29)





 
Hi @majssssa,
 Unfortunately, that the data in that paper is outdated and is not compatible with the current version of fDOG. However, if you want, we can provide you a new set of ortholog groups for the same taxa used in the paper (A. thaliana, Glycine max, Medicago truncatula, Populus trichocarpa, Solanum lycopersicum, Vitis vinifera, Oryza sativa, Sorghum bicolor and Zea mays), which can be used with fDOG.
 Best,
 Vinh

**Comment by trvinh** [comment]
I will let you know later. I will need to generate the data first :)

**Comment by majssssa** [comment]
Thank you very much for your help


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BIONF/fDOG"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月27日(星期一) 下午4:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BIONF/fDOG] 4180 low-copy lineologous candidate nuclear genes from 9 representative angiosperms (Issue #29)





 
I will let you know later. I will need to generate the data first :)

**Comment by trvinh** [comment]
Hi @majssssa 
you can download the data here https://applbio.biologie.uni-frankfurt.de/download/core-sets/angiosperm.tar.gz 
Regards,
Vinh

**Comment by majssssa** [comment]
好，非常感谢您的帮助。
