### ISSUE TITLE
ERROR: Cannot find seed sequence in genome of reference species for Dracaena_cambodiana_DN10000_c0_g1_i1.p1!

### ISSUE THREAD

**Issue by majssssa** [BIONF/fDOG#31]
I encountered the following error while running fDOG
ERROR: Cannot find seed sequence in genome of reference species for `Dracaena_cambodiana_DN10000_c0_g1_i1.p1!
This is my code `fdog.run --seqFile Dracaena_cambodiana.pep --jobName test --refspec ARATH@3702@3`.Also, nothing appears in the window when I run this command.Finally, the above error occurs.
This is my seqFile 
>Dracaena_cambodiana_DN10000_c0_g1_i1.p1
MVAVFNKELLSCYLITLKLKQTVEAGLAKSQPNSPTPKPPLRLTQGQPPQPPVPRADSEWVISIREKLDEARQEQAACPWAKLSIYRVPKSLREGDSKAYVPQVVSLGPYHRGKHHLRGMDHHKWRALHKVLRRTGHDVELYLDSIKMLEERARACYEGSLSLTSNEFVETMVLDGIFILELFRGAAGEGFKQLGYSHNDPVFAMRATMHSIQRDMIMLENQIPLFVLDRLLALQICKPEQSGLVATLAVQFFDPLIPTDEPLRKIDRNKLQSTSPSLKATAAVFDP
>Dracaena_cambodiana_DN10004_c0_g1_i1.p1
VKEEKLSKDSNSKNGAKSGGELKRASKRPDLKAVSKMIENHQVLYPEKMIGHLPGIDVGDQFLSRAEMCVLGLHNHWLNGIDYMGQSFAKLERYKNYTFPLAICIVLSGMYEDDLDNSEDIVYTGQGGHDLLGSKHQVSDQKMERGNLALKNNCDLGVPVRVVRGHELKSSYSGKVYTYDGLYRVIKTWAEKGVSGFTVYKYKLRRVEGQPVLRTNQVQFTRAT
>Dracaena_cambodiana_DN10014_c0_g1_i1.p1
VRLLLLVGPAQVQIQQLLLEKLPEHFDAVSPSRNLNDDVARLIVNQFRWLDFLVDSRGFAEKLMEVLSIAPLLLKKEIIGSLPEIIGDQNSSMVIASLERLLQEDSEVIVPVLDSFSNLNLDDQLQEQAVTIALSCIRTVDAEHMPHLLRFLLLSATSVNVGRIISQIREQLKFVGVSDPCVAKQKMLKGKYLADSTEASILDALRSSLRFKNTTCEAIFKELKSLDHPRDHKVIDVWFLMLIYTNGGSLQKNAEKIL
>Dracaena_cambodiana_DN10015_c0_g1_i1.p1
MTPNANTLPPPQTPTPNSLIMAGKSPKPSILTDGLLFFGGAAVALLLFLTLYSFLSPLAPSSPSLPFRHSLPLLANPHSPRHHHNSCDSNLHIDPSSPNLYDDPSVSYTLSYSGSLITDWDRKRTNWLHSHPTFAAKRNRILMVSGSQPGPCRNPIGDHLLLRFYKNKADYCRLHDIDLFYNTALLQPDMFSFWAKIPVVRAAMVAHPEAEWIWWVDSDAAITDMEFELPLDRYEGYNLVLHGWRDLVYKAKSWTSLNAGVFLMRNCQWSLDFIDTWSRMGPQSPEYERWGRIQRAIFKDKLYAASDDQTGIAYLLLEEKRKWADKIYLESAFYFEGYWVEIVNKLERIEAEYLEMDRRVKGLRRRRAEKVAVAYGRMREELLEKQGVRRGMEGWRRPFITHFTGCQPCSGDHNKEYSGENCFGGMQRALNFADNQVLRSYGFRHERLVNSTGVRPLPFDFPAAG*
>Dracaena_cambodiana_DN10025_c0_g1_i1.p1
MSPCGGVGHEPAVLQLQKWGYLQFQLEPSEFRLASISPTRDLLLLLSYQCEALLLPLLLGKFQSENICEPNSSEQVITCIPDDVDSAQCSKNDEESVKGAALPILESSSASKSYPVISGVKSLAWGHS
>Dracaena_cambodiana_DN10026_c0_g1_i1.p1
VICLGIFFRSWPSPRPSFIRDISQQNSSESYGLVHVCALGGEFLCRLAVFAILERLGSQILYSMFASFCLMAAIFLRRNIVETKGKTLQEIEISLRQPE*
>Dracaena_cambodiana_DN10027_c0_g1_i1.p4
MSPTDRGGPTSSAVGSLHLLPSELLHSILLRLPLPDLLRLRSLSRLLLSSISAPEFRRTYQSTSPWLFLFQKRPPRSSLLRGFDPRSARWFTFPSLSALIAAPALPPGDDLYLLA
>Dracaena_cambodiana_DN10028_c0_g1_i1.p1
MGFTAAELERLISSNARILIVAPAIPRLEFWQAFIGGDNRKDLVSVLTRNRGLITHDIVSGIAPKMLLLKEHGLSQRDIVGLVKRGHGFITRSSKTIEAVLNSAKELGLDTKSPMFGHTLSSLVSFSSDSFKAKMEIFRGFGWSEEELLAAFKKAPSFLHLSEENIREKMEFLVGRAGCKQSYIALNPLLLTFSLEKRLRPRHYVMEVLKSKGIMGRARFSKIMCLTEKKFVESVILPCKEQVPNIHELYIA
>Dracaena_cambodiana_DN10030_c0_g1_i1.p1
LFRNPLSLSLLRKFFPKQISNLMGYLSCRAESSISTCRSISAISPSQSPTSTTNTKKKHLKPYKSLQNQENDDDDDDKSPCRRIEHFTYAELESATNNFSNSSLLGRGS

**Comment by trvinh** [comment]
Please prefer to this wiki to make sure you have the correct input data for fDOG https://github.com/BIONF/fDOG/wiki/Input-and-Output-Files (and https://github.com/BIONF/fDOG/wiki/Use-standalone-version)
- For `fdog.run`, it must be a SINGLE sequence in FASTA format
- The reference species (specified with `--refspec`) must be present in the blast database directory

**Comment by trvinh** [comment]
@majssssa This issue is solved, right?
