### ISSUE TITLE
Addition of Taxa doesnt seems to be working with fdog.addTaxa

### ISSUE THREAD

**Issue by swttalyan** [BIONF/fDOG#38]
Hello, I am trying to add some genomes from ncbi for which I have downloaded AA fasta sequences in a directoty and I would like to use "fdog.addTaxa -i  Fasta_files -m Mapping_file.txt -c " if I use it this way it doesnt read "_protein.faa" files then tried "fdog.addTaxa -i  Fasta_files/* -m Mapping_file.txt -c " Now with this it read all fasta files but gives an error "unrecognized arguments"

Could you please help, what wrong I am doing, when I tried with fdog.addTaxon -f XX_protein.fa -i  9606 -c, this was running and iterating through all sequenec in fasta file but with error to so I am not sure whether I could the information created with fdog.addTaxon.

Any help will be highly appreciated.

**Comment by swttalyan** [comment]
I would like to use all the non vertebrate species from ncbi "https://ftp.ncbi.nlm.nih.gov/genomes/refseq/vertebrate_other/"

**Comment by trvinh** [comment]
Hi @swttalyan,
I need more information in order to reproduce the issue. Since I have tested both the functions with my data and they still worked. I used the same command that you have tried: `fdog.addTaxa -i Fasta_files -m Mapping_file.txt -c`. Both `-i Fasta_files` or `-i Fasta_files/` will work, but not `-i Fasta_files/*`.
```
vinh@wks15:/share/project/vinh/test/fdog/addTaxa$ fdog.addTaxa -i Fasta_files -m Mapping_file.txt -c
WARNING: 9607 not found in NCBI taxonomy database!
WARNING: rank of 9605 is not SPECIES (genus)
WARNING: 9605 not found in NCBI taxonomy database!
Parsing genome for 2 species...
  0%|                                                                                                                                  | 0/2 [00:00<?, ?it/s]WARNING: Sequence IDs contain pipe(s). They will be replaced by "_"!
Please check the /home/vinh/fdog_data_2023/searchTaxa_dir/UNK9607@9607@240119/UNK9607@9607@240119.fa.mapping file for details!
WARNING: Sequence IDs contain pipe(s). They will be replaced by "_"!
Please check the /home/vinh/fdog_data_2023/searchTaxa_dir/UNK9605@9605@240119/UNK9605@9605@240119.fa.mapping file for details!
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 28.24it/s]

Creating Blast DB for 2 species...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  7.16it/s]
PID 2837391
Doing annotation for /home/vinh/fdog_data_2023/searchTaxa_dir/UNK9607@9607@240119/UNK9607@9607@240119.fa...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 46/46 [00:07<00:00,  5.91it/s]
Finished in 8.059s
PID 2839315
Doing annotation for /home/vinh/fdog_data_2023/searchTaxa_dir/UNK9605@9605@240119/UNK9605@9605@240119.fa...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 45/45 [00:08<00:00,  5.43it/s]
Finished in 8.564s
==> Adding 2 taxa finished in 20.164s
==> Output for UNK9605@9605@240119 can be found in /home/vinh/fdog_data_2023/searchTaxa_dir, /home/vinh/fdog_data_2023/coreTaxa_dir, /home/vinh/fdog_data_2023/annotation_dir
```

My `Mapping_file.txt` looks like this:
```
vinh@wks15:/share/project/vinh/test/fdog/addTaxa$ head Mapping_file.txt
#filename	tax_id
test.extended.fa	9607
tr_Q90XQ7_DANRE.extended.fa	9605
```

And this is an example with `fdog.addTaxon`

```
vinh@wks15:/share/project/vinh/test/fdog/addTaxa$ fdog.addTaxon -f Fasta_files/tr_Q90XQ7_DANRE.extended.fa -i 9999 -c
NCBI taxon info: 9999 Urocitellus parryii
Species name	UROPA@9999@240119
Parsing FASTA file...
WARNING: Sequence IDs contain pipe(s). They will be replaced by "_"!
Please check the /home/vinh/fdog_data_2023/searchTaxa_dir/UROPA@9999@240119/UROPA@9999@240119.fa.mapping file for details!

Creating Blast DB...


Building a new DB, current time: 01/19/2024 14:56:35
New DB name:   /home/vinh/fdog_data_2023/coreTaxa_dir/UROPA@9999@240119/UROPA@9999@240119
New DB title:  /home/vinh/fdog_data_2023/searchTaxa_dir/UROPA@9999@240119/UROPA@9999@240119.fa
Sequence type: Protein
Keep MBits: T
Maximum file size: 3000000000B
Adding sequences from FASTA; added 45 sequences in 0.0176709 seconds.


PID 2846204
Doing annotation for /home/vinh/fdog_data_2023/searchTaxa_dir/UROPA@9999@240119/UROPA@9999@240119.fa...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 45/45 [00:08<00:00,  5.49it/s]
Finished in 8.469s

==> Output for UROPA@9999@240119 can be found in /home/vinh/fdog_data_2023/searchTaxa_dir, /home/vinh/fdog_data_2023/coreTaxa_dir, /home/vinh/fdog_data_2023/annotation_dir
```

Which fDOG version are you using? Please make sure to install the latest one (v0.1.26).
Did you put all the `_protein.faa` into your `Fasta_files` folder? Does that folder contains only the fasta files that you mention in your `Mapping_file.txt`? How do you know that it doesn't read all the fasta files? Please show me the log file with the error message.

Best,
Vinh

**Comment by swttalyan** [comment]
Many thanks for your response, yes I am using the latest version of the fDOG(v0.1.26).
I managed to get it running, there are lot of conditions for naming of the fasta files as the name shouldn;t contain more than one "_" or some special character therefore I renamed all fasta file to protein1.faa, protein2.faa and so on. and it run until creating blast db and now I am getting the following error:

`/home/user/annotation_tools/COILS2/COILS2 -f < "/workspace/fdog/annotation_dir/tmp/2745623/LETRE@7753@240123_XP_061403495_1.fa"
Error running
`
for all the sequences and species.

**Comment by swttalyan** [comment]
Also cann I know how much time it will take to add approx 100 vertebrate species, I am only interested in getting Fas score for a human seed protein from all vertebrate species, so this step of COILS2 required while calculating phyloprofile ?

**Comment by trvinh** [comment]
Hi @swttalyan ,

if you encountered a problem with COILS2, please check the [FAQs of FAS](https://github.com/BIONF/FAS/wiki/FAQ#Error-with-COILS2). Please make sure to test FAS before using fDOG.

The most time consuming step is the feature annotation. The runtime depends on the number of CPUs used for the annotation. In our benchmark, it took about 15min for a gene set with 20,000 proteins using 64 CPUs. To calculate the FAS scores, annotations are required for both the seed species (in your case, human) and the search/query species (the other vertebrate species). Therefore, you still need to run the annotation for species.

Best,
Vinh

**Comment by swttalyan** [comment]
Many thanks Vinh, unfortunately I am encountering no problems in running setupFAS and all annotations tools are installed problems occurs only while adding Taxa with fdog.addTaxa.

**Comment by swttalyan** [comment]
Now the with the separate steps it seems to be working.
`Doing annotation for /workspace/fdog/searchTaxa_dir/LETRE@7753@240123/LETRE@7753@240123.fa...
  1%|          | 244/35015 [00:55<1:05:03,  8.91it/s]`
Lets see I will continue this way, yes I am using conda env and have FAS and fDOG both are install. Thanks, hopefully it runs smoothly after this for getting the phyloprofiles.
