### ISSUE TITLE
Issue with fdog-Assembly: ModuleNotFoundError for 'fdog.fDOGassembly'

### ISSUE THREAD

**Issue by Somnous1998** [BIONF/fDOG#46]
Dear Professor,

I am attempting to use the fdog-Assembly tool to find homologous genes in an unannotated genome based on a seed gene dataset. However, I encountered a ModuleNotFoundError: No module named 'fdog.fDOGassembly' error, and it appears that the fdog.fDOGassembly module has been removed.

Could you please confirm if fdog no longer supports operations on unannotated genomes?

Thank you very much for your assistance. I look forward to your response.

Sincerely,
Zechen Tang

**Comment by ebersber** [comment]
Dear Zechen Tang,
Thank you very much for pointing this out. Could you please specify from which branch you have downloaded fDOG? Please use the branch fdog_goes_assembly (https://github.com/BIONF/fDOG/tree/fdog_goes_assembly). If you did use this branch, please indicate so.
Kind regards,
Ingo Ebersberger

**Comment by Somnous1998** [comment]
Dear Ingo Ebersberger,

Thank you very much for your response. I downloaded and configured fDOG from the branch you specified (fdog_goes_assembly: https://github.com/BIONF/fDOG/tree/fdog_goes_assembly). However, when I attempted to use it, I encountered an error indicating that the module does not exist. Further investigation suggests that it may have been removed.

Could you please provide further guidance or confirm if the module has indeed been removed?

Thank you for your assistance.

Kind regards,
Zechen Tang
![image](https://github.com/BIONF/fDOG/assets/63293232/f6dcac04-8a7e-4d94-9b52-8fb74f72458e)
![image](https://github.com/BIONF/fDOG/assets/63293232/4dbfc58e-a797-4552-a3f2-96fb43c78f57)

**Comment by mueli94** [comment]
Dear Zechen Tang,

thank you for pointing this out. 
The fDOG-Assembly module was removed from the fDOG master branch in an earlier version and exists only in its own branch (fdog_goes_assembly).  Please double-check if you are using the correct branch and the latest version. You can follow the following instructions to install fDOG-assembly. 

`# clone repo
git clone https://github.com/BIONF/fDOG.git

#navigate in fDOG folder
cd fDOG

#checkout branch
git checkout --track origin/fdog_goes_assembly

#install fDOG
python setup.py develop

#setup fDOG
fdog.setup -d <directory_for_fDOG_data>

#setup FAS
fas.setup -t </annotation_tools>
`
Please, let me know if you still encounter the same error. 

Kind regards,

Hannah

**Comment by Somnous1998** [comment]
Dear Hannah,

Thank you for your help. I have now managed to include the module by obtaining the correct version from GitHub. However, I have some further questions I hope you can assist with:

I noticed that the --augustusRefSpec AUGUSTUSREFSPEC parameter is required. Does this mean that I need to pre-train Augustus in my environment, or do I need to provide specific commands to train Augustus during the setup? I did not find any specific instructions regarding configuring Augustus.

The --gene option requires alignment and HMM files. When running fdog.run on a protein dataset, the three specified folders (--searchpath /path/to/your/searchTaxa_dir, --corepath /path/to/your/coreTaxa_dir, and --annopath /path/to/your/annotation_dir) do not include HMM and alignment files. However, according to your 2009 publication, these files are necessary. I am a bit confused if I missed a step where these core gene HMM and alignment files should have been generated during fdog.run. Is the process as follows: aligning sequences of orthologous genes, building, training, and calibrating pHMM using HMMER, and then combining all generated files into one file to be used as an input for fdog.run?

Currently, I am running fDOG version 0.1.32 with fdog.assembly version 0.0.1.

Thank you very much for your patience and assistance, and I apologize for any inconvenience.

Kind regards,
Zechen Tang

**Comment by mueli94** [comment]
Dear Zechen Tang, 
in fDOG-Assembly we have implemented two different gene prediction methods, namely Augustus and MetaEuk. Currently, MetaEuk is the default gene prediction method. If you want to use augustus, you have to use --augustus as a parameter, and additionally, the --augustusRefSpec parameter. Please remove the --metaEukDB parameter and replace it with --augustus if you want to use Augustus. 

There was indeed a bug using --strict, thank you. It is now fixed, so please update fDOG-Assembly. Nevertheless, I want to mention that using --strict can decrease the number of reported orthologs by fDOG-Assembly or lead to no ortholog reported at all. I recommend using fDOG-Assembly without the parameter --strict and by using the species as reference (--refSpec) that is related closest to your species under investigation. 

Currently, a batch gene search is not implemented in fDOG-Assembly. Maybe we can deliver that in a future update. 

Kind regards,

Hannah

**Comment by Somnous1998** [comment]
Dear Hannah,

Thank you very much for your detailed response and the provided information. Based on your guidance, I will make the following adjustments to my command:

Remove the --metaEukDB parameter and replace it with --augustus.
Add the --augustus parameter alongside --augustusRefSpec.

I have also noted your recommendation about not using the --strict parameter, as it can decrease the number of reported orthologs or lead to no orthologs being reported at all. I will update fDOG-Assembly to the latest version to ensure the bug fix is applied.

Regarding batch gene search, thank you for clarifying that it is not currently implemented in fDOG-Assembly. I look forward to any future updates that might include this feature.

Thank you again for your patience and support.

Kind regards,
Zechen Tang
