### ISSUE TITLE
fdogs.run error messages

### ISSUE THREAD

**Issue by sashulkaSh** [BIONF/fDOG#5]
Hello! 
I tested fdogs.run with some sequences and it seems to me that error messages are displayed a little incorrectly. 
Below I will give the errors that I encountered so that it would be more convenient for you to catch them!

1) When outdir doesnt exists:
_fdogs.run --cpu 12 --input input_dir/ --jobName job1 --refspec ANOGA@7165@3 --outpath ./job1_S1 --fasoff_

```
Traceback (most recent call last):
  File "/home/sh/.local/bin/fdogs.run", line 8, in <module>
    sys.exit(main())
  File "/home/sh/.local/lib/python3.7/site-packages/fdog/runMulti.py", line 415, in main
    multiLog = open(outpath + '/' + jobName + '_log.txt', "w")
FileNotFoundError: [Errno 2] No such file or directory: '/data/fs/hpc/cluws/sh-worms/test/job1_S1/job1_log.txt'
```

2) When program FAS doesnt found:
_fdogs.run --cpu 12 --input input_dir/ --jobName job1 --refspec ANOGA@7165@3 --outpath ./2_
```
PID 189193
Starting compiling core orthologs...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 20.88it/s]
==> Core compiling finished in 0.363 sec
Searching orthologs for...
seq1.fa
test_ref.fa
job1_S1_DN10018_c0_g1_i21.fa
seq2.fa.fa
==> Ortholog search finished in 4.044 sec
Joining single outputs...
Traceback (most recent call last):
  File "/home/sh/.local/bin/fdogs.run", line 8, in <module>
    sys.exit(main())
  File "/home/sh/.local/lib/python3.7/site-packages/fdog/runMulti.py", line 444, in main
    finalFa = joinOutputs(outpath, jobName, seeds, keep)
  File "/home/sh/.local/lib/python3.7/site-packages/fdog/runMulti.py", line 158, in joinOutputs
    os.remove(outpath + '/' + seqName + '.fa')
FileNotFoundError: [Errno 2] No such file or directory: '/data/fs/hpc/cluws/sh-worms/test/2/seq1.fa'

```
the beginning of this log looks a little funny, because no search is going on, files are not created, but it is written as if all this has been done))

3) When fdogs.run cant find orthologs least for one sequence from input (or if --refspec is selected incorrectly):
 _fdogs.run --cpu 12 --input input_dir/ --jobName job1 --refspec ARATH@3702@3 --outpath ./3 --fasoff_
```
PID 154327
Starting compiling core orthologs...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [01:49<00:00, 27.30s/it]
==> Core compiling finished in 109.272 sec
Searching orthologs for...
seq1.fa
test_ref.fa
job1_S1_DN10018_c0_g1_i21.fa
seq2.fa.fa
==> Ortholog search finished in 35.291 sec
Joining single outputs...
Traceback (most recent call last):
  File "/home/sh/.local/bin/fdogs.run", line 8, in <module>
    sys.exit(main())
  File "/home/sh/.local/lib/python3.7/site-packages/fdog/runMulti.py", line 444, in main
    finalFa = joinOutputs(outpath, jobName, seeds, keep)
  File "/home/sh/.local/lib/python3.7/site-packages/fdog/runMulti.py", line 158, in joinOutputs
    os.remove(outpath + '/' + seqName + '.fa')
FileNotFoundError: [Errno 2] No such file or directory: '/data/fs/hpc/cluws/sh-worms/test/3/test_ref.fa'
```
in this case the program just breaks, file *extended.fa is empty. When the running time of the program is 5 minutes (processing a pair of sequences), it is not as unpleasant as in the case when the program worked for 2 days on a large number of sequences... 

I hope my message will be useful to you!

**Comment by trvinh** [comment]
Hi @sashulkaSh ,
many thanks for your post! It is indeed very helpful for me to catch the errors. I will try to improve them and let you know the status.
Best,
Vinh

**Comment by trvinh** [comment]
hi @sashulkaSh, 
I have added some checks to fdogs.run in the latest version. Could you test it please? 
Regarding to the last issue with the empty final extended.fa, fdog will now check if the file is empty or can not be found and the run will be stopped with a proper warning. It cannot, however, catch this issue right after one starts running fdog, since that file is almost the final output. The intermediate results, for example the core ortholog groups, could be successfully created. 
Best,
Vinh
